# Generated by Django 5.1.5 on 2025-01-23 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField()),
                ('sentiment_category', models.CharField(max_length=50)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('input_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='sentiment.inputdata')),
            ],
        ),
    ]
